vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /uploads/images/products/images
            upload_destination: '%kernel.project_dir%/public/uploads/images/products/images'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        product_attachment:
            uri_prefix: /uploads/images/products/attachments
            upload_destination: '%kernel.project_dir%/public/uploads/images/products/attachments'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
